### ISSUE TITLE
Pick a version of minitest-rails

### ISSUE THREAD

**Issue by elskwid** [newleaders/thincloud-test#6]
This project has a dependency on minitest-rails. Version 0.1.3 is using [minitest-rails](https://github.com/blowmage/minitest-rails) which uses the default Rails `test\…` directory structure but the thincloud-test generators all look for tests in a `spec\…` directory.

@phlipper is maintaining a fork at [minitest-rails](https://github.com/phlipper/minitest-rails) that has been modified to use the `spec` directory.

Should the project be changed to use the fork or should it use the minitest-rails defaults?

**Comment by phlipper** [comment]
I will not be maintaining my fork and it would be prudent to adopt the conventions used in the official release.

**Comment by elskwid** [comment]
I'm working on a pull request to do that. Thanks @phlipper!

**Comment by elskwid** [comment]
Closed by #8
