### ISSUE TITLE
Create factories directory

### ISSUE THREAD

**Issue by elskwid** [newleaders/thincloud-test#7]
Since we already create the directories expected by minitest-rails should we also create the `factories`directory expected by `factory_girl_rails`? (added in #5).

**Comment by elskwid** [comment]
Any thoughts on this one?

**Comment by phlipper** [comment]
:+1:

**Comment by elskwid** [comment]
#9 modifies the gem to be a Rails engine. We're not generating any of the directories as they will be created by the `minitest-rails` generators when called.

**Comment by phlipper** [comment]
FYI: the `factories/` directory is not created by the `minitest-rails` generator.

**Comment by elskwid** [comment]
`>_<`

**Comment by elskwid** [comment]
Thanks @phlipper. I appreciate your help.
